initial_position: [25, 100] # default position for testing
final_position: [650, 530] # default position for testing

wheelchair_length: 0.7 # in meters
wheelchair_width: 0.3 # in meters

safety_distance: 0.05 # how close the wheelchair can approach obstacles
lidar_radius: 30 # get the scanning range in meters
distance_tolerance: 0.05 # in meters
map_figure_size: 12

colliders: './data_storage/colliders.csv'
grid_save: './data_storage/grid.csv'
skeleton_save: './data_storage/skeleton.csv'
path_save: './data_storage/path.csv'

# VFH config
sector_angle: 1 # alpha constant of VFH
a: 1
b: 1
l: 3 # max is 18. 6 is suggested
vfh_time_delay: 500 # ms
vfh_threshold: 0.1

# LIDAR blind angles
blind_spot_range: [135, 225] # (from, to) range of blind spot in degrees
lidar_height_threshold: 0.15 # cm

# Island configuration
font_size: 10
islands_data_path: "data_storage/islands"
islands_file_headers: ["ID", "Name", "Coordinate_x", "Coordinate_y"]
