initial_position: [25, 100] # default position for testing
final_position: [650, 530] # default position for testing

wheelchair_length: 0.7 # in meters
wheelchair_width: 0.3 # in meters

safety_distance: 0.5 # how close the wheelchair can approach obstacles
lidar_radius: 30 # get the scanning range in meters
distance_tolerance: 0.5 # in meters
map_figure_size: 12

colliders: './data_storage/colliders.csv'
grid_save: './data_storage/grid.csv'
skeleton_save: './data_storage/skeleton.csv'
path_save: './data_storage/path.csv'

# VFH config
sector_angle: 1
a: 1
b: 1
l: 6 # max is 18
vfh_threshold: 0.05
